default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taggd-lite_development

test:
  <<: *default
  database: taggd-lite_test

production:
  <<: *default
  database: taggd-lite_production
  username: taggd-lite
  password: <%= ENV['TAGGD-LITE_DATABASE_PASSWORD'] %>
